# Generated by Django 5.2.5 on 2025-11-12 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='student',
        ),
        migrations.RemoveField(
            model_name='revision',
            name='student',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.DeleteModel(
            name='Revision',
        ),
    ]
