# Generated by Django 5.2.5 on 2025-12-14 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_quiz_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='upload_date',
            new_name='uploaded_at',
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_a',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_b',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_c',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_d',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_semester',
            field=models.CharField(max_length=20),
        ),
    ]
