# Generated by Django 6.0.5 on 2026-10-01 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_flashcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_date', models.DateField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_days', to='core.student')),
            ],
            options={
                'ordering': ['-study_date'],
                'constraints': [models.UniqueConstraint(fields=('student', 'study_date'), name='unique_student_study_day')],
            },
        ),
    ]
